In [104]:
%pip install kaggle

Requirement already satisfied: kaggle in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (1.7.4.5)
Requirement already satisfied: bleach in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2025.7.14)
Requirement already satisfied: charset-normalizer in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (6.31.1)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: colorama in c:\users\aryar\appdata\roaming\python\python312\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

print("Connected Successfully")

Connected Successfully

In [106]:
!kaggle datasets download -d ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
retail-orders.zip: Skipping, found more recently modified local copy (use --force to force download)

In [107]:
import zipfile

with zipfile.ZipFile("retail-orders.zip","r") as zip_ref:
    zip_ref.extractall("retail_orders")

In [108]:
import os
os.listdir()

['Order_Pattern.ipynb', 'retail-orders.zip', 'retail_orders']

In [109]:
[f for f in os.listdir() if f.endswith('.zip')]

['retail-orders.zip']

In [110]:
import os
print(os.getcwd())

c:\Users\aryar\Desktop\Order Pattern and Retention Analysis

In [111]:
# Cleaning the dataset
import pandas as pd
df=pd.read_csv('retail_orders/orders.csv',na_values=['Not Available','unknown'])
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [112]:
df=pd.read_csv("retail_orders/orders.csv")
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [113]:
df = pd.read_csv('retail_orders/orders.csv',na_values=['Not Available','unknown'])
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [114]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [115]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [116]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [117]:
df['discount']=df['list_price']*df['discount_percent']*0.01
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0

In [118]:
df['sale_price']=df['list_price']+df['discount']
df['profit']=df['sale_price']-df['cost_price']
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,265.2,25.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,751.9,151.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,10.5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,979.2,199.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,21.0,1.0

In [119]:
df.describe()
df.columns.tolist()
#order_date is object

['order_id',
 'order_date',
 'ship_mode',
 'segment',
 'country',
 'city',
 'state',
 'postal_code',
 'region',
 'category',
 'sub_category',
 'product_id',
 'cost_price',
 'list_price',
 'quantity',
 'discount_percent',
 'discount',
 'sale_price',
 'profit']

In [120]:
#dropping unnecessary columns
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")
df.info()
#df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          9994 non-null   int64
 1   order_date        9994 non-null   datetime64[ns]
 2   ship_mode         9988 non-null   object
 3   segment           9994 non-null   object
 4   country           9994 non-null   object
 5   city              9994 non-null   object
 6   state             9994 non-null   object
 7   postal_code       9994 non-null   int64
 8   region            9994 non-null   object
 9   category          9994 non-null   object
 10  sub_category      9994 non-null   object
 11  product_id        9994 non-null   object
 12  cost_price        9994 non-null   int64
 13  list_price        9994 non-null   int64
 14  quantity          9994 non-null   int64
 15  discount_percent  9994 non-null   int64
 16  discount          9994 non-null   float64
 17  sale_price        9994 non-null   float64
 18  profit            9994 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(6), object(9)
memory usage: 1.4+ MB

In [121]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,265.2,25.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,751.9,151.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,10.5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,979.2,199.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,21.0,1.0

In [122]:
df.drop(columns=['list_price','discount_percent','cost_price'],inplace=True)
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,265.2,25.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,751.9,151.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,10.5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,979.2,199.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,21.0,1.0

In [123]:
pip install pandas sqlalchemy psycopg2-binary

Requirement already satisfied: pandas in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (2.9.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: greenlet>=1 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\aryar\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [133]:
#connecting jupyter notebook to PostgreSQL usinh username, passwords, host, port, database
from sqlalchemy import create_engine
username= 'postgres' 
password= 'Password'
host= 'localhost'
port= '5432'
database= 'order_pattern_and_analysis'
engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#loading data into postgresql
table_name="order_pattern"
df.to_sql(table_name, engine, if_exists="replace", index=False) #no index column is stored in sql table
print(f"Data successfully loaded into table'{table_name}' in database'{database}',")

Data successfully loaded into table'order_pattern' in database'order_pattern_and_analysis',